name:                pi
version:             0.1.0.0
github:              "githubuser/pi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pi#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- haskeline
- mtl
- prettyprinter
- text

executables:
  pi:
    main:                Main.hs
    source-dirs:         src
    other-modules:
    - Interaction.Human
    - Interaction.JSON
    - Interaction
    - Interpreter
    - PiMonad
    - PPrint
    - Syntax
    - Utilities
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
# build-tools:
#   - happy
#   - alex
