name:                pi
version:             0.1.0.0
github:              "githubuser/pi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pi#readme>

dependencies:
- base >= 4.7 && < 5
- array
- ansi-terminal
- bytestring
- containers
- haskeline
- lexer-applicative
- mtl
- regex-applicative
- prettyprinter
- srcloc
- text

build-tools:
- happy

executable:
  main:                Main.hs
  source-dirs:         src
  ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -fno-warn-orphans

tests:
  pi-tests:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
